//Search
export const SEARCH_KEYWORD = "SEARCH_KEYWORD";
export const UPDATE_SEARCH_RESULT = "UPDATE_SEARCH_RESULT";
export const UPDATE_SUGGESTION = "UPDATE_SUGGESTION";

//Upload
export const UPLOAD_FILE = "UPLOAD_FILE";
export const UPDATE_UPLOAD_STATUS = "UPDATE_UPLOAD_STATUS";
export const UPDATE_UPLOAD_PROGRESS = "UPDATE_UPLOAD_PROGRESS";
